global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: devel
  isHubCluster: false
  namespaces:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
    policies:
    openshift-pipelines:
  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    openshift-pipelines:
      name: openshift-pipelines-operator-rh
      namespace: openshift-operators
  argoProjects:
    - dev
    - eso
  applications:
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: eso
      chart: openshift-external-secrets
      chartVersion: 0.0.*
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
