apiVersion: v1
kind: Secret
metadata:
  name: qtodo-client-id
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-options: PrunePropagationPolicy=orphan
  labels:
    validatedpatterns.io/cleanup: delete
type: Opaque
stringData:
  client-id: "{{ include "rh-keycloak.qtodo.oidc.clientId" . }}"
