apiVersion: v1
kind: Secret
metadata:
  name: qtodo-client-id
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  client-id: "{{ include "rh-keycloak.qtodo.oidc.clientId" . }}"
