apiVersion: v2
name: acs-secured-cluster
description: Red Hat Advanced Cluster Security Secured Cluster Services
type: application
version: 1.0.1
appVersion: "4.11"
keywords:
  - security
  - runtime-protection
  - admission-control
  - zero-trust
maintainers:
  - name: Validated Patterns Team
home: https://validatedpatterns.io/patterns/layered-zero-trust/
sources:
  - https://github.com/validatedpatterns/layered-zero-trust