{{- if .Values.chartIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    route.openshift.io/termination: reencrypt
    route.openshift.io/destination-ca-certificate-secret: keycloak-tls
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  name: keycloak-ingress
  namespace: keycloak-system
spec:
  defaultBackend:
    service:
      name: keycloak-service-trusted
      port:
        number: 8443
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{- end }}
    http:
      paths:
      - backend:
          service:
            name: keycloak-service
            port:
              number: 8443
        pathType: ImplementationSpecific
{{- end }}
