{{- if and .Values.rhtpa.enabled .Values.rhtpa.oidc.enabled }}
---
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Values.rhtpa.oidc.clientSecretName }}
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.rhtpa.oidc.clientSecretName }}
    template:
      type: Opaque
      data:
        password: "{{ `{{ .password | trim }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.rhtpa.oidc.clientSecretVaultPath }}
      property: {{ .Values.rhtpa.oidc.clientSecretVaultKey }}
{{- end }}