---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-qtodo-restarter
  namespace: qtodo
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["qtodo"]
  verbs: ["get", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-qtodo-restarter
  namespace: qtodo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-qtodo-restarter
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.global.namespace }}
