apiVersion: v2
name: certmanager
description: A Helm chart to deploy OpenShift cert-manager operator with proper DNS nameserver configuration for Validated Patterns.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
home: https://github.com/validatedpatterns/layered-zero-trust
maintainers:
  - name: Validated Patterns Team
    email: validatedpatterns@googlegroups.com
icon: https://validatedpatterns.io/images/validated-patterns.png
keywords:
  - cert-manager
  - ssl
  - tls
  - certificates
  - openshift
