{{- if and .Values.central.enabled (not .Values.central.adminPassword.useExternalSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.central.adminPassword.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acs-central.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "36"
type: Opaque
stringData:
  password: {{ .Values.central.adminPassword.password | default (randAlphaNum 32) | quote }}
{{- end }}