{{- if and .Values.central.enabled .Values.integration.keycloak.enabled }}
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Values.integration.keycloak.clientSecret.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acs-central.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "36"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.integration.keycloak.clientSecret.secretName }}
    template:
      type: Opaque
      data:
        {{ .Values.integration.keycloak.clientSecret.secretKey }}: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: secret/data/hub/infra/acs/acs-central
      property: admin-password
{{- end }}
