apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integration.keycloak.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acs-central.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "32"