apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '41'
  labels:
    app: qtodo-db
  name: qtodo-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.postgresql.port }}-tcp
    port: {{ .Values.postgresql.port }}
    protocol: TCP
    targetPort: {{ .Values.postgresql.port }}
  selector:
    app: qtodo-db
  sessionAffinity: None
  type: ClusterIP
