{{- if and .Values.enabled .Values.loki.enabled }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.loki.name }}
  namespace: {{ .Values.loki.namespace }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "41"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: {{ .Values.loki.size }}
  storage:
    schemas:
      - version: v13
        effectiveDate: "2022-06-01"
    secret:
      name: {{ .Values.loki.storageSecretName }}
      type: s3
  storageClassName: {{ include "netobserv.lokiStorageClassName" . }}
  tenants:
    mode: openshift-network
{{- end }}
