---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: qtodo-sbom-attestation
  namespace: {{ .Values.global.namespace }}
spec:
  description: This Task can be used to attest the SBOM for the qtodo image.

  params:
{{- include "rhtas.tasks.sigstoreParamsDesc" . | nindent 4 }}
    - description: Image to generate the SBOM for
      name: image
      type: string
    - description: SBOM file path to attach to the attestation
      name: sbom-file
      type: string
      default: qtodo-sbom.json
    - description: SBOM file format to attach to the attestation
      name: sbom-format
      type: string
      default: spdxjson

  workspaces:
    - name: source
      description: The workspace where the SBOM file will be found.

  volumes:
{{- if .Values.rhtas.spire.enabled }}
    - name: spiffe-workload-api
      csi:
        driver: csi.spiffe.io
        readOnly: true
{{- end }}
    - name: rhtas-functions
      configMap:
        name: rhtas-functions
        defaultMode: 0755
{{- if and .Values.rhtas.oidc.enabled (ne .Values.rhtas.oidc.clientSecretName "") }}
    - name: rhtas-oidc-client-secret
      secret:
        secretName: {{ .Values.rhtas.oidc.clientSecretName }}
        defaultMode: 0400
{{- end }}

  steps:
    - image: {{ .Values.tasks.images.cosign }}
      name: sbom-attestation
      resources: {}
      env:
{{- include "rhtas.tasks.sigstoreEnvVars" . | nindent 8 }}
        - name: SBOM_FILE
          value: $(workspaces.source.path)/$(params.sbom-file)
        - name: SBOM_FORMAT
          value: $(params.sbom-format)
      volumeMounts:
{{- if .Values.rhtas.spire.enabled }}
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
{{- end }}
        - name: rhtas-functions
          mountPath: /usr/local/lib
          readOnly: true
{{- if and .Values.rhtas.oidc.enabled (ne .Values.rhtas.oidc.clientSecretName "") }}
        - name: rhtas-oidc-client-secret
          mountPath: /run/secrets/rhtas/oidc
          readOnly: true
{{- end }}
      script: |
        #!/usr/bin/env bash

        source /usr/local/lib/rhtas-functions

        attest_sbom_image "$(params.image)"