apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openshift-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: openshift-config
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: pull-secret-reader
