apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: qtodo
  name: qtodo
  namespace: qtodo
{{- if or .Values.app.images.main.registry.auth (and .Values.global.registry.enabled .Values.global.registry.vaultPath) }}
imagePullSecrets:
  - name: {{ .Values.app.images.main.registry.secretName }}
{{- end }}