apiVersion: v1
kind: ConfigMap
metadata:
  name: qtodo-config-env
  namespace: {{ .Release.Namespace }}
data:
{{- if eq .Values.app.oidc.enabled true }}
  QUARKUS_OIDC_ENABLED: "true"
  QUARKUS_OIDC_AUTH_SERVER_URL: "{{ include "qtodo.oidc.url" . }}"
  QUARKUS_OIDC_CLIENT_ID: "{{ include "qtodo.oidc.clientId" . }}"
  QUARKUS_OIDC_APPLICATION_TYPE: "{{ .Values.app.oidc.applicationType }}"
  QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_PATHS: "{{ .Values.app.oidc.authenticatedPaths }}"
  QUARKUS_HTTP_AUTH_PERMISSION_AUTHENTICATED_POLICY: "{{ .Values.app.oidc.authenticatedPolicy }}"
  QUARKUS_OIDC_AUTHENTICATION_FORCE_REDIRECT_HTTPS_SCHEME: "true"
{{- if and .Values.app.oidc.clientAssertion.enabled (not .Values.app.oidc.clientSecret.enabled) }}
  QUARKUS_OIDC_CREDENTIALS_JWT_SOURCE: "bearer"
  QUARKUS_OIDC_CREDENTIALS_JWT_TOKEN_PATH: "{{ .Values.app.oidc.clientAssertion.jwtTokenPath }}"
{{- if eq .Values.app.oidc.provider "entraid" }}
  QUARKUS_OIDC_CREDENTIALS_JWT_AUDIENCE: "{{ include "qtodo.jwt.audience" . }}"
{{- end }}
{{- end }}
{{- end }}
