apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '51'
    {{- if eq .Values.app.tls.serviceServing true }}
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.app.tls.secret | quote }}
    {{- end }}
  labels:
    app: qtodo
  name: qtodo
  namespace: qtodo
spec:
  ports:
  - name: {{ printf "%s-tcp" (include "qtodo.app.port" .) }}
    port: {{ template "qtodo.app.port" . }}
    protocol: TCP
    targetPort: {{ template "qtodo.app.port" . }}
  selector:
    app: qtodo
  sessionAffinity: None
  type: ClusterIP