apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: qtodo
    argocd.argoproj.io/instance: qtodo
  name: qtodo
spec:
  port:
    targetPort: {{ printf "%s-tcp" (include "qtodo.app.port" .) }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: {{ .Values.app.route.termination }}
  to:
    kind: Service
    name: qtodo
    weight: 100
  wildcardPolicy: None